### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by ticoniq** [migo1/Recipie-App#12]
We are two in our team 

https://github.com/migo1/Recipie-App/projects/1

@migo1
@ticoniq

**Comment by topeogunleye** [comment]
Hi 👋 team,

You have done a magnificent job so far! 🚀
There are a few issues you need to address to move on to the next project, but you're almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646096-51e043e6-1884-4ace-a446-3068f22b6b6f.gif)

### To highlight 🌟
- The board setup is on point! ✅
- The PR title and description are professional, containing all the necessary information. 👏

## Required Changes ♻️
- Ensure that each card on the Kanban board has the number of points in the [Xpt] prefix. 📌
<img width="246" alt="image" src="https://github.com/migo1/Recipie-App/assets/52934128/78fc89b9-064b-4849-9e68-9ae22e35346f">

- Include a card specifically for "Writing unit and integration tests" on the Kanban board. 📝
- Make sure tasks are distributed fairly among all team members, promoting equal responsibility and learning opportunities. 🤝

## Optional suggestions
_Every comment with the [OPTIONAL] prefix isn't crucial enough to stop the approval of this PR. However, I strongly advise you to consider them as they can enhance your code._

You can also ponder on:
- N/A

Cheers and Happy coding!🎉🎉🎉

Feel free to drop any questions or comments in the PR thread if clarity eludes you.
Always remember to tag @topeogunleye in your queries to ensure I get the notification.

**_Please refrain from opening a new Pull Request for re-reviews. Use the same Pull Request submitted for the initial review, be it valid or invalid unless advised otherwise._**

------
_As stipulated in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a set number of reviews per project (you can find the exact number in your Dashboard). If you feel the code review wasn't fair, you have the option to request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- Fair distribution of tasks ✔️
- Good use of Kanban board ✔️

 ## Required Changes ♻️
_Check the comments under the review._
- [x] I can see the tasks you added are yet to be assigned, I will encourage you to assign it so that it would be a duty of someone.
![image](https://github.com/migo1/Recipie-App/assets/86200356/fa600352-6f9f-4f49-bdbe-93fe71cd5336)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @topeogunleye & @migo1  👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Proper kanban template is used ✔
- Each card is assigned a team member ✔
- Tasks are distributed fairly ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
